"use client";

import { useCallback, useRef, useState } from "react";
import { Crosshair, Database, Download, Eye, Map, Navigation, Search, X } from "lucide-react";
import { AtlasMap, type CameraJourney, type JourneyStage } from "@/components/map/atlas-map";
import { AtlasNav } from "@/components/shell/atlas-nav";
import { demoDiscoveryResults, demoGeoJsonExport, demoIntent, demoVectorFeatures } from "@/lib/demo/discovery";
import { config } from "@/lib/config";
import type { AtlasFeature, DiscoveryResult } from "@/types/geo";

const demoCoordinates: [number, number] = [77.5946, 12.9716];
const exampleQuery = "Find commercial roofs with solar panel installations within 200 metres of open drainage";
const examples = [exampleQuery, "Locate unpaved roads intersecting cleared forest patches", "Find built-up areas near drainage channels"];
const journeyStages: JourneyStage[] = ["WORLD OVERVIEW", "CONTINENT", "COUNTRY", "REGION", "LOCAL AREA", "STREET LEVEL"];
type View = "global" | "journey" | "street" | "local";

export default function Home() {
  const [query, setQuery] = useState(exampleQuery); const [submitted, setSubmitted] = useState(exampleQuery); const [view, setView] = useState<View>("global"); const [stage, setStage] = useState<JourneyStage>("WORLD OVERVIEW"); const [journey, setJourney] = useState<CameraJourney>(); const [journeyId, setJourneyId] = useState(0); const [locationLabel, setLocationLabel] = useState("Global Atlas"); const [locationDetail, setLocationDetail] = useState("No location captured"); const [locationState, setLocationState] = useState<"idle" | "requesting" | "captured" | "unavailable">("idle"); const [streetStatus, setStreetStatus] = useState("Coverage not checked"); const [selected, setSelected] = useState<DiscoveryResult>(); const [showDiscovery, setShowDiscovery] = useState(false); const [error, setError] = useState(""); const [visible, setVisible] = useState({ search: true, hazard: false, infrastructure: true }); const sequence = useRef(0);
  const results = config.demoMode ? demoDiscoveryResults : [];
  const features: AtlasFeature[] = view === "global" ? [] : [...demoDiscoveryResults, ...demoVectorFeatures];
  const startJourney = (target: [number, number], demo: boolean, detail?: string) => { sequence.current += 1; setJourneyId(sequence.current); setError(""); setSelected(undefined); setShowDiscovery(false); setView("journey"); setStage("WORLD OVERVIEW"); setStreetStatus("Checking configured street-imagery coverage…"); setLocationLabel(demo ? "DEMO LOCATION · Bengaluru" : "Captured coordinates"); setLocationDetail(detail || (demo ? "Demo hierarchy: Asia · India · Karnataka · Bengaluru" : `${target[1].toFixed(5)}° N · ${target[0].toFixed(5)}° E · locality unavailable`)); setJourney({ id: sequence.current, target, demo }); };
  const locateMe = () => { if (!navigator.geolocation) { setLocationState("unavailable"); setError("Geolocation is unavailable in this browser. Use Preview demo journey instead."); return; } setError(""); setLocationState("requesting"); navigator.geolocation.getCurrentPosition((position) => { const target: [number, number] = [position.coords.longitude, position.coords.latitude]; const detail = `${target[1].toFixed(5)}° N · ${target[0].toFixed(5)}° E · ±${Math.round(position.coords.accuracy)} m · ${new Date(position.timestamp).toLocaleTimeString()} · locality unavailable`; setLocationState("captured"); startJourney(target, false, detail); }, (reason) => { setLocationState("unavailable"); setError(`Location was not captured (${reason.message}). Your coordinates remain private; preview the demo journey instead.`); }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }); };
  const skipJourney = () => { setJourney(undefined); setStreetStatus("Coverage unavailable — showing local demo panorama"); setView("street"); setStage("STREET LEVEL"); };
  const handleJourneyComplete = useCallback(() => { setJourney(undefined); setStreetStatus("Coverage unavailable — showing local demo panorama"); setView("street"); setStage("STREET LEVEL"); }, []);
  const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(query.trim() || exampleQuery); setShowDiscovery(true); if (view === "global") startJourney(demoCoordinates, true); };
  const exportGeoJson = () => { const source = JSON.stringify(demoGeoJsonExport(submitted), null, 2); const url = URL.createObjectURL(new Blob([source], { type: "application/geo+json" })); const link = document.createElement("a"); link.href = url; link.download = "geosathi-demo-discovery.geojson"; link.click(); URL.revokeObjectURL(url); };
  return <main className="world-atlas premium-v2">
    <div className="map-workspace"><AtlasMap features={features} visible={visible} selected={selected} journey={journey} onJourneyStage={setStage} onJourneyComplete={handleJourneyComplete} onSelect={(feature) => { const result = results.find((candidate) => candidate.id === feature.id); if (result) { setSelected(result); setShowDiscovery(true); } }}/></div>
    <AtlasNav />
    <header className="world-header"><form onSubmit={submit}><Search size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Natural language GeoAI query"/><button>DISCOVER</button></form><div className="demo-status"><i/> DEMO MODE · SYNTHETIC EVIDENCE</div></header>
    <div className="world-meta"><span>{stage}</span><b>{locationLabel}</b><small>{locationDetail}</small>{view === "journey" && <div className="journey-feedback"><i/><span>{streetStatus}</span></div>}</div>{view !== "global" && <div className="journey-breadcrumb" aria-label="Journey progress">{journeyStages.map((item) => <span className={journeyStages.indexOf(item) <= journeyStages.indexOf(stage) ? "done" : ""} key={item}>{item.replace(" OVERVIEW", "")}</span>)}</div>}
    {view === "global" && <section className="global-intro"><div className="intro-kicker"><Map size={15}/> Global discovery workspace</div><h1>Start with a place.<br/>Then ask a spatial question.</h1><p className="intro-note">A deterministic, judge-safe journey through Bengaluru is ready. Live location is requested only when you activate Locate Me.</p><div className="global-actions"><button className="yellow-action" onClick={locateMe}><Crosshair size={17}/> {locationState === "requesting" ? "REQUESTING LOCATION…" : "LOCATE ME"}</button><button className="dark-action" onClick={() => startJourney(demoCoordinates, true)}><Navigation size={17}/> PREVIEW DEMO JOURNEY</button></div>{error && <p className="location-error">{error}</p>}<div className="continent-picker"><span>EXPLORE CONTEXT</span><button onClick={() => startJourney(demoCoordinates, true)}>Asia</button><button onClick={() => startJourney(demoCoordinates, true)}>India</button><button onClick={() => startJourney(demoCoordinates, true)}>Karnataka</button></div><div className="query-gallery"><span>EXAMPLE QUERIES</span>{examples.map((example) => <button key={example} onClick={() => { setQuery(example); setSubmitted(example); startJourney(demoCoordinates, true); }}>{example}</button>)}</div></section>}
    {view === "journey" && <button className="skip-button" onClick={skipJourney}>SKIP ANIMATION</button>}
    {(view === "local" || view === "street" || showDiscovery) && <aside className="discovery-dock"><div className="dock-head"><div><p>QUERY INTERPRETATION · DEMO</p><h2>{submitted}</h2></div><button onClick={() => setShowDiscovery(false)} aria-label="Close discovery panel"><X size={16}/></button></div><div className="intent-row"><span>VISUAL</span><b>{demoIntent.visualTargets.join(" · ")}</b><span>VECTOR</span><b>{demoIntent.osmFeatureTypes.join(" · ")}</b><span>SPATIAL</span><b>{demoIntent.distanceMetres} m buffer · within distance</b></div><div className="candidate-row">{results.map((result) => <button key={result.id} className={selected?.id === result.id ? "selected" : ""} onClick={() => setSelected(result)}><Eye size={15}/><span><b>{result.title}</b><small>{result.imageTileId} · {result.relationships[0].distanceMetres} m to drain</small></span><em>{result.score?.toFixed(2)}<small>demo</small></em></button>)}<button className="export-button" onClick={exportGeoJson}><Download size={14}/> GEOJSON</button></div></aside>}
    {view === "street" && <section className="street-view" aria-label="Demo panorama viewer"><div className="street-panorama"><div className="panorama-horizon"/><div className="panorama-grid"/><span className="panorama-label">DEMO PANORAMA — NOT VERIFIED AT THIS LOCATION</span><span className="compass-cue">N · 018°</span></div><div className="street-info"><p>STREET-LEVEL FALLBACK</p><h2>{locationLabel}</h2><span>{locationDetail}</span><small>{streetStatus}. Generated local demo panorama; no Mapillary token or verified coverage is configured.</small><div><button className="yellow-action" onClick={() => { setView("local"); setJourney({ id: journeyId + 1, target: demoCoordinates, demo: true }); }}>RETURN TO MAP</button><button className="dark-action" onClick={() => { setJourney(undefined); setView("global"); setStage("WORLD OVERVIEW"); }}>RETURN TO GLOBE</button></div></div></section>}
    {selected && <aside className="evidence-card"><button onClick={() => setSelected(undefined)} aria-label="Close evidence"><X size={15}/></button><p>OBJECT GROUNDING · DEMO</p><h2>{selected.title}</h2><div className="grounding-box"><i/><span>{selected.imageTileId}</span></div><dl><dt>OBJECT</dt><dd>{selected.groundedObjects[0].label} · illustrative {selected.score?.toFixed(2)}</dd><dt>OSM</dt><dd>{selected.osmFeatures[0].type} · {selected.osmFeatures[0].osmId}</dd><dt>RELATION</dt><dd>{selected.relationships[0].explanation}</dd></dl></aside>}
    <footer className="osm-footer"><Database size={13}/> © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a> · street imagery attribution is separate; demo panorama is locally generated</footer>
  </main>;
}
