"use client";
import { useMemo, useState } from "react";
import { Compass, Copy, Database, Layers3, MapPin, Search, X, ZoomIn, AlertTriangle, Eye, Route } from "lucide-react";
import { AtlasMap } from "@/components/map/atlas-map";
import { demoFeatures } from "@/lib/demo/fixtures";
import { config } from "@/lib/config";
import type { AtlasFeature } from "@/types/geo";

const kindLabels = { search: "AI Search Results", hazard: "Road Hazards", infrastructure: "Infrastructure Features" };
export default function Home() {
  const [query, setQuery] = useState(""); const [submitted, setSubmitted] = useState(""); const [selected, setSelected] = useState<AtlasFeature>(); const [visible, setVisible] = useState({ search: true, hazard: true, infrastructure: true }); const [hazardFilter, setHazardFilter] = useState("all"); const [drawer, setDrawer] = useState(true);
  const features = useMemo(() => config.demoMode ? demoFeatures.filter(f => hazardFilter === "all" || f.kind !== "hazard" || f.hazardType === hazardFilter) : [], [hazardFilter]);
  const searchResults = features.filter(f => f.kind === "search" && (!submitted || f.title.toLowerCase().includes(submitted.toLowerCase()) || submitted.length > 2));
  const submit = (e: React.FormEvent) => { e.preventDefault(); setSubmitted(query.trim()); setDrawer(true); };
  const coordinates = selected?.geometry.type === "Point" ? selected.geometry.coordinates : selected?.bounds ? [selected.bounds[0], selected.bounds[1]] : undefined;
  return <main className="atlas-shell">
    <nav className="rail" aria-label="Primary navigation"><div className="brand-mark"><Compass size={22}/></div><span className="brand">GeoSathi<br/><b>ATLAS</b></span><div className="rail-nav"><button className="nav-active" aria-label="Explore map"><MapPin size={19}/><span>Explore</span></button><button aria-label="Focus incidents"><AlertTriangle size={19}/><span>Incidents</span></button><button aria-label="Focus data layers"><Layers3 size={19}/><span>Layers</span></button></div><div className="rail-foot">v0.1<br/>FIELD</div></nav>
    <section className="workspace">
      <header className="command"><form onSubmit={submit}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search imagery, corridors, or infrastructure…" aria-label="Natural-language geographic search"/><button type="submit">Search</button>{query && <button type="button" className="icon-button" aria-label="Clear search" onClick={()=>{setQuery("");setSubmitted("")}}><X size={16}/></button>}</form><div className="status"><span className={config.demoMode ? "demo-dot" : "offline-dot"}/>{config.demoMode ? "DEMO DATA — SYNTHETIC" : "BACKEND NOT CONNECTED"}</div></header>
      <AtlasMap features={features} visible={visible} selected={selected} onSelect={setSelected}/>
      <div className="map-title"><span>GEO / BENGALURU TEST SECTOR</span><small>12.972° N · 77.575° E</small></div>
      <div className="scale"><i/> 500 m</div>
      <aside className={`results ${drawer ? "open" : "closed"}`} aria-label="Search results"><div className="panel-head"><div><p className="eyebrow">RETRIEVAL</p><h1>{submitted ? `“${submitted}”` : "Explore evidence"}</h1></div><button className="icon-button" onClick={()=>setDrawer(!drawer)} aria-label="Toggle results drawer">{drawer ? <X size={17}/> : <Search size={17}/>}</button></div><p className="panel-copy">{config.demoMode ? "Synthetic fixtures for interaction testing; no real imagery or model output is shown." : "Connect a confirmed backend contract to search georeferenced evidence."}</p>{config.demoMode && <div className="example">TRY: <button onClick={()=>{setQuery("drainage");setSubmitted("drainage")}}>drainage corridor</button></div>}<div className="result-list">{searchResults.length ? searchResults.map(f=><button className={`result ${selected?.id===f.id?"selected":""}`} key={f.id} onClick={()=>setSelected(f)}><div className="result-symbol"><Eye size={17}/></div><div className="result-copy"><b>{f.title}</b><span>SYNTHETIC DEMO · {f.source}</span><small>{f.bounds ? `${f.bounds[1].toFixed(3)}° N, ${f.bounds[0].toFixed(3)}° E` : "Geometry supplied"}</small></div>{f.score !== undefined && <em>Illustrative similarity<br/>{f.score.toFixed(2)} (demo)</em>}</button>) : <div className="empty">No synthetic candidates match this query. Adjust the phrase or clear the search.</div>}</div></aside>
      <aside className="layers" aria-label="Map layers"><div className="layer-heading"><Layers3 size={15}/> LAYERS</div><label><input type="checkbox" checked readOnly/> <span className="swatch osm"/>OSM Street Map</label>{(Object.keys(visible) as Array<keyof typeof visible>).map(k=><label key={k}><input type="checkbox" checked={visible[k]} onChange={e=>{setVisible({...visible,[k]:e.target.checked});if(!e.target.checked&&selected?.kind===k)setSelected(undefined)}}/><span className={`swatch ${k}`}/>{kindLabels[k]} <small>demo</small></label>)}<div className="map-legend"><span><i className="legend-search"/>Search footprint</span><span><i className="legend-hazard"/>Hazard point</span><span><i className="legend-corridor"/>Survey corridor</span></div><div className="filter"><span>HAZARD TYPE</span><select value={hazardFilter} onChange={e=>{setHazardFilter(e.target.value);if(selected?.kind==="hazard"&&e.target.value!=="all"&&selected.hazardType!==e.target.value)setSelected(undefined)}} aria-label="Filter hazard type"><option value="all">All types</option><option value="surface">Surface</option><option value="flooding">Flooding</option></select></div></aside>
      {selected && <aside className="inspector" aria-label="Evidence inspector"><div className="panel-head"><div><p className="eyebrow">EVIDENCE INSPECTOR · DEMO</p><h2>{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(undefined)} aria-label="Close inspector"><X size={17}/></button></div><div className="geometry-preview">{selected.geometry.type.toUpperCase()}<span>{selected.kind === "hazard" ? <AlertTriangle size={30}/> : selected.kind === "infrastructure" ? <Route size={30}/> : <Eye size={30}/>}</span></div><dl><dt>DATA ORIGIN</dt><dd>Synthetic demo · {selected.source}</dd><dt>STATUS</dt><dd>{selected.status || "demo candidate"}</dd>{selected.score !== undefined && <><dt>SIMILARITY</dt><dd>Illustrative · {selected.score.toFixed(2)} (demo)</dd></>}{selected.timestamp && <><dt>TIME</dt><dd>{selected.timestamp}</dd></>}{selected.evidence && <><dt>EVIDENCE</dt><dd>{selected.evidence}</dd></>}</dl>{coordinates && <div className="coords">{coordinates[1].toFixed(5)}° N&nbsp;&nbsp; {coordinates[0].toFixed(5)}° E <button onClick={()=>navigator.clipboard?.writeText(`${coordinates[1]}, ${coordinates[0]}`)} aria-label="Copy coordinates"><Copy size={14}/></button></div>}<button className="zoom-button" onClick={()=>setSelected({...selected})}><ZoomIn size={15}/> Zoom to feature</button></aside>}
      <footer className="attribution-note"><Database size={13}/> Base map © OpenStreetMap contributors · Synthetic fixtures are locally bundled</footer>
    </section>
  </main>;
}
